version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
